//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElementsFilter {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ElementsFilter.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to will find out all the elements whose BuiltInCategory ==.
        /// </summary>
        internal static string BuiltInCategoryDes {
            get {
                return ResourceManager.GetString("BuiltInCategoryDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to will find out all the elements whose category ==.
        /// </summary>
        internal static string CategoryDes {
            get {
                return ResourceManager.GetString("CategoryDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to will find out all the elements whose.
        /// </summary>
        internal static string CommonDes {
            get {
                return ResourceManager.GetString("CommonDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This filter can not be deleted..
        /// </summary>
        internal static string DeleteFilterWarning {
            get {
                return ResourceManager.GetString("DeleteFilterWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to input should be a double value.
        /// </summary>
        internal static string DoubleInputMessage {
            get {
                return ResourceManager.GetString("DoubleInputMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acquiring failed..
        /// </summary>
        internal static string FailedAcquiring {
            get {
                return ResourceManager.GetString("FailedAcquiring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New filter failed.
        /// </summary>
        internal static string FailedNewFilterWarning {
            get {
                return ResourceManager.GetString("FailedNewFilterWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to will find out all the elements whose family name ==.
        /// </summary>
        internal static string FamilyDes {
            get {
                return ResourceManager.GetString("FamilyDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter information.
        /// </summary>
        internal static string FilterInfo {
            get {
                return ResourceManager.GetString("FilterInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Error.
        /// </summary>
        internal static string InputError {
            get {
                return ResourceManager.GetString("InputError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input.
        /// </summary>
        internal static string InputInvalid {
            get {
                return ResourceManager.GetString("InputInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to input should be an integer value.
        /// </summary>
        internal static string IntInputMessage {
            get {
                return ResourceManager.GetString("IntInputMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The boolean expression is invalid..
        /// </summary>
        internal static string InvalidBooleanExpWarning {
            get {
                return ResourceManager.GetString("InvalidBooleanExpWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This string is invalid..
        /// </summary>
        internal static string InvalidWarning {
            get {
                return ResourceManager.GetString("InvalidWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string has been used yet..
        /// </summary>
        internal static string NewNameCaption {
            get {
                return ResourceManager.GetString("NewNameCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click yes to change a new name?.
        /// </summary>
        internal static string NewNameMessage {
            get {
                return ResourceManager.GetString("NewNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select one filter first..
        /// </summary>
        internal static string NoSelectedWarning {
            get {
                return ResourceManager.GetString("NoSelectedWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        internal static string Run {
            get {
                return ResourceManager.GetString("Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to will find out all the elements whose symbol name ==.
        /// </summary>
        internal static string SymbolDes {
            get {
                return ResourceManager.GetString("SymbolDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to will find out all the elements whose type ==.
        /// </summary>
        internal static string TypeDes {
            get {
                return ResourceManager.GetString("TypeDes", resourceCulture);
            }
        }
    }
}
