//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Revit.SDK.Samples.PowerCircuit.CS.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Revit.SDK.Samples.PowerCircuit.CS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap AddToCircuit {
            get {
                object obj = ResourceManager.GetObject("AddToCircuit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Cancel {
            get {
                object obj = ResourceManager.GetObject("Cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string CaptionInformation {
            get {
                return ResourceManager.GetString("CaptionInformation", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap CreateCircuit {
            get {
                object obj = ResourceManager.GetObject("CreateCircuit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DisconnectPanel {
            get {
                object obj = ResourceManager.GetObject("DisconnectPanel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap EditCircuit {
            get {
                object obj = ResourceManager.GetObject("EditCircuit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected element has already been included in the circuit!.
        /// </summary>
        internal static string ElementInCircuit {
            get {
                return ResourceManager.GetString("ElementInCircuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The circuit does not include the selected element!.
        /// </summary>
        internal static string ElementNotInCircuit {
            get {
                return ResourceManager.GetString("ElementNotInCircuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add the selected element to Circuit. Please verify that The Number of Poles and Voltage for the selected element match the Number of Poles and Voltage for the Circuit..
        /// </summary>
        internal static string FailedToAddElement {
            get {
                return ResourceManager.GetString("FailedToAddElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create circuit with selected elements. Please verify that The Number of Poles and Voltage for selected elements match with each other..
        /// </summary>
        internal static string FailedToCreateCircuit {
            get {
                return ResourceManager.GetString("FailedToCreateCircuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to disconnect panel from the power circuit!.
        /// </summary>
        internal static string FailedToDisconnectPanel {
            get {
                return ResourceManager.GetString("FailedToDisconnectPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to remove selected element from the power circuit!.
        /// </summary>
        internal static string FailedToRemoveElement {
            get {
                return ResourceManager.GetString("FailedToRemoveElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to assign the selected element to the circuit. Please verify that The Number of Poles and Voltage for the selected element match the Number of Poles and Voltage for the Circuit..
        /// </summary>
        internal static string FailedToSelectPanel {
            get {
                return ResourceManager.GetString("FailedToSelectPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected element has no unused electrical connector!.
        /// </summary>
        internal static string NoUsableConnector {
            get {
                return ResourceManager.GetString("NoUsableConnector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active document is null..
        /// </summary>
        internal static string NullActiveDocument {
            get {
                return ResourceManager.GetString("NullActiveDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Failed.
        /// </summary>
        internal static string OperationFailed {
            get {
                return ResourceManager.GetString("OperationFailed", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap RemoveFromCircuit {
            get {
                object obj = ResourceManager.GetObject("RemoveFromCircuit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected element is not electrical!.
        /// </summary>
        internal static string SelectElectricalComponent {
            get {
                return ResourceManager.GetString("SelectElectricalComponent", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap SelectPanel {
            get {
                object obj = ResourceManager.GetObject("SelectPanel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select elements first!.
        /// </summary>
        internal static string SelectPowerElements {
            get {
                return ResourceManager.GetString("SelectPowerElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Circuit.
        /// </summary>
        internal static string tipAddToCircuit {
            get {
                return ResourceManager.GetString("tipAddToCircuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string tipCancel {
            get {
                return ResourceManager.GetString("tipCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Power Circuit.
        /// </summary>
        internal static string tipCreateCircuit {
            get {
                return ResourceManager.GetString("tipCreateCircuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect Panel from Circuit.
        /// </summary>
        internal static string tipDisconnectPanel {
            get {
                return ResourceManager.GetString("tipDisconnectPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Circuit.
        /// </summary>
        internal static string tipEditCircuit {
            get {
                return ResourceManager.GetString("tipEditCircuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from circuit.
        /// </summary>
        internal static string tipRemoveFromCircuit {
            get {
                return ResourceManager.GetString("tipRemoveFromCircuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Panel for the Circuit.
        /// </summary>
        internal static string tipSelectPanel {
            get {
                return ResourceManager.GetString("tipSelectPanel", resourceCulture);
            }
        }
    }
}
