//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Revit.SDK.Samples.GridCreation.Properties
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MacroCSharpSamples.Samples.GridCreation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please adjust the values and try again!.
        /// </summary>
        internal static string AjustValues {
            get {
                return ResourceManager.GetString("AjustValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinate can not be null!.
        /// </summary>
        internal static string CoordinateCannotBeNull {
            get {
                return ResourceManager.GetString("CoordinateCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinate is not in a correct format!.
        /// </summary>
        internal static string CoordinateFormatWrong {
            get {
                return ResourceManager.GetString("CoordinateFormatWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Degree can not be negative!.
        /// </summary>
        internal static string DegreeCannotBeNegative {
            get {
                return ResourceManager.GetString("DegreeCannotBeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Degree can not be null!.
        /// </summary>
        internal static string DegreeCannotBeNull {
            get {
                return ResourceManager.GetString("DegreeCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Degree is not in a correct format!.
        /// </summary>
        internal static string DegreeFormatWrong {
            get {
                return ResourceManager.GetString("DegreeFormatWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start degree and end degree can not be so close!.
        /// </summary>
        internal static string DegreesAreTooClose {
            get {
                return ResourceManager.GetString("DegreesAreTooClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Degree should be within the range of 0 - 360!.
        /// </summary>
        internal static string DegreeWithin0To360 {
            get {
                return ResourceManager.GetString("DegreeWithin0To360", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance can not be negative!.
        /// </summary>
        internal static string DistanceCannotBeNegative {
            get {
                return ResourceManager.GetString("DistanceCannotBeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance can not be null!.
        /// </summary>
        internal static string DistanceCannotBeNull {
            get {
                return ResourceManager.GetString("DistanceCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance is not in a correct format!.
        /// </summary>
        internal static string DistanceFormatWrong {
            get {
                return ResourceManager.GetString("DistanceFormatWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cm.
        /// </summary>
        internal static string DUT_CENTIMETERS {
            get {
                return ResourceManager.GetString("DUT_CENTIMETERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;.
        /// </summary>
        internal static string DUT_DECIMAL_FEET {
            get {
                return ResourceManager.GetString("DUT_DECIMAL_FEET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;.
        /// </summary>
        internal static string DUT_DECIMAL_INCHES {
            get {
                return ResourceManager.GetString("DUT_DECIMAL_INCHES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;.
        /// </summary>
        internal static string DUT_FEET_FRACTIONAL_INCHES {
            get {
                return ResourceManager.GetString("DUT_FEET_FRACTIONAL_INCHES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;.
        /// </summary>
        internal static string DUT_FRACTIONAL_INCHES {
            get {
                return ResourceManager.GetString("DUT_FRACTIONAL_INCHES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m.
        /// </summary>
        internal static string DUT_METERS {
            get {
                return ResourceManager.GetString("DUT_METERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m.
        /// </summary>
        internal static string DUT_METERS_CENTIMETERS {
            get {
                return ResourceManager.GetString("DUT_METERS_CENTIMETERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mm.
        /// </summary>
        internal static string DUT_MILLIMETERS {
            get {
                return ResourceManager.GetString("DUT_MILLIMETERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Start point and end point of arc grids are too close.
        /// </summary>
        internal static string EndPointsTooClose {
            get {
                return ResourceManager.GetString("EndPointsTooClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create one or more arc grids..
        /// </summary>
        internal static string FailedToCreateArcGrids {
            get {
                return ResourceManager.GetString("FailedToCreateArcGrids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create one or more grids. .
        /// </summary>
        internal static string FailedToCreateGrids {
            get {
                return ResourceManager.GetString("FailedToCreateGrids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create one or more radial grids. .
        /// </summary>
        internal static string FailedToCreateRadialGrids {
            get {
                return ResourceManager.GetString("FailedToCreateRadialGrids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete some of the selected lines or arcs!.
        /// </summary>
        internal static string FailedToDeletedLinesOrArcs {
            get {
                return ResourceManager.GetString("FailedToDeletedLinesOrArcs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to set label of grid to : .
        /// </summary>
        internal static string FailedToSetLabel {
            get {
                return ResourceManager.GetString("FailedToSetLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to Create Grids.
        /// </summary>
        internal static string FailureCaptionCreateGrids {
            get {
                return ResourceManager.GetString("FailureCaptionCreateGrids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to Delete Lines/Arcs.
        /// </summary>
        internal static string FailureCaptionDeletedLinesOrArcs {
            get {
                return ResourceManager.GetString("FailureCaptionDeletedLinesOrArcs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Value.
        /// </summary>
        internal static string FailureCaptionInvalidValue {
            get {
                return ResourceManager.GetString("FailureCaptionInvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to Set Label.
        /// </summary>
        internal static string FailureCaptionSetLabel {
            get {
                return ResourceManager.GetString("FailureCaptionSetLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label can not be null!.
        /// </summary>
        internal static string LabelCannotBeNull {
            get {
                return ResourceManager.GetString("LabelCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A same label has already existed!.
        /// </summary>
        internal static string LabelExisted {
            get {
                return ResourceManager.GetString("LabelExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The two labels can&apos;t be same!.
        /// </summary>
        internal static string LabelsCannotBeSame {
            get {
                return ResourceManager.GetString("LabelsCannotBeSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number should be an integer between 0 and 200!.
        /// </summary>
        internal static string NumberBetween0And200 {
            get {
                return ResourceManager.GetString("NumberBetween0And200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number can not be null!.
        /// </summary>
        internal static string NumberCannotBeNull {
            get {
                return ResourceManager.GetString("NumberCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number is not in a correct format!.
        /// </summary>
        internal static string NumberFormatWrong {
            get {
                return ResourceManager.GetString("NumberFormatWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The two numbers can not be both zero!.
        /// </summary>
        internal static string NumbersCannotBeBothZero {
            get {
                return ResourceManager.GetString("NumbersCannotBeBothZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radius can not be negative or zero!.
        /// </summary>
        internal static string RadiusCannotBeNegativeOrZero {
            get {
                return ResourceManager.GetString("RadiusCannotBeNegativeOrZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radius can not be null!.
        /// </summary>
        internal static string RadiusCannotBeNull {
            get {
                return ResourceManager.GetString("RadiusCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radius is not in a correct format!.
        /// </summary>
        internal static string RadiusFormatWrong {
            get {
                return ResourceManager.GetString("RadiusFormatWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  That may be caused by one or more of following reasons:.
        /// </summary>
        internal static string Reasons {
            get {
                return ResourceManager.GetString("Reasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spacing can not be negative or zero!.
        /// </summary>
        internal static string SpacingCannotBeNegativeOrZero {
            get {
                return ResourceManager.GetString("SpacingCannotBeNegativeOrZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spacing can not be null!.
        /// </summary>
        internal static string SpacingCannotBeNull {
            get {
                return ResourceManager.GetString("SpacingCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spacing is not in a correct format!.
        /// </summary>
        internal static string SpacingFormatWrong {
            get {
                return ResourceManager.GetString("SpacingFormatWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Spacings between grids are too small.
        /// </summary>
        internal static string SpacingsTooSmall {
            get {
                return ResourceManager.GetString("SpacingsTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start degree should be less than end degree!.
        /// </summary>
        internal static string StartDegreeShouldBeLessThanEndDegree {
            get {
                return ResourceManager.GetString("StartDegreeShouldBeLessThanEndDegree", resourceCulture);
            }
        }
    }
}
