//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeCheckingConcreteExample.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodeCheckingConcreteExample.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom.
        /// </summary>
        internal static string Abottom {
            get {
                return ResourceManager.GetString("Abottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        internal static string Aleft {
            get {
                return ResourceManager.GetString("Aleft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all sections.
        /// </summary>
        internal static string AllSections {
            get {
                return ResourceManager.GetString("AllSections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applies to the following sections: .
        /// </summary>
        internal static string AppliesToSections {
            get {
                return ResourceManager.GetString("AppliesToSections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        internal static string Aright {
            get {
                return ResourceManager.GetString("Aright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        internal static string Atop {
            get {
                return ResourceManager.GetString("Atop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        internal static string AxisArea {
            get {
                return ResourceManager.GetString("AxisArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dencity.
        /// </summary>
        internal static string AxisDencity {
            get {
                return ResourceManager.GetString("AxisDencity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displacment/Deflection.
        /// </summary>
        internal static string AxisDisplacmentDeflection {
            get {
                return ResourceManager.GetString("AxisDisplacmentDeflection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force.
        /// </summary>
        internal static string AxisForce {
            get {
                return ResourceManager.GetString("AxisForce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string AxisHeight {
            get {
                return ResourceManager.GetString("AxisHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        internal static string AxisLength {
            get {
                return ResourceManager.GetString("AxisLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moment.
        /// </summary>
        internal static string AxisMoment {
            get {
                return ResourceManager.GetString("AxisMoment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spacing.
        /// </summary>
        internal static string AxisSpacing {
            get {
                return ResourceManager.GetString("AxisSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary bottom.
        /// </summary>
        internal static string AxxBottom {
            get {
                return ResourceManager.GetString("AxxBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary top.
        /// </summary>
        internal static string AxxTop {
            get {
                return ResourceManager.GetString("AxxTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary bottom.
        /// </summary>
        internal static string AyyBottom {
            get {
                return ResourceManager.GetString("AyyBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary top.
        /// </summary>
        internal static string AyyTop {
            get {
                return ResourceManager.GetString("AyyTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bar diameter.
        /// </summary>
        internal static string BarDiameter {
            get {
                return ResourceManager.GetString("BarDiameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axial load.
        /// </summary>
        internal static string BeamFX {
            get {
                return ResourceManager.GetString("BeamFX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axial load (Fx).
        /// </summary>
        internal static string BeamFX_Note {
            get {
                return ResourceManager.GetString("BeamFX_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lateral shear force.
        /// </summary>
        internal static string BeamFY {
            get {
                return ResourceManager.GetString("BeamFY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lateral shear force (Fy).
        /// </summary>
        internal static string BeamFY_Note {
            get {
                return ResourceManager.GetString("BeamFY_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shear force.
        /// </summary>
        internal static string BeamFZ {
            get {
                return ResourceManager.GetString("BeamFZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shear force (Fz).
        /// </summary>
        internal static string BeamFZ_Note {
            get {
                return ResourceManager.GetString("BeamFZ_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torsional moment.
        /// </summary>
        internal static string BeamMX {
            get {
                return ResourceManager.GetString("BeamMX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torsional moment (Mx).
        /// </summary>
        internal static string BeamMX_Note {
            get {
                return ResourceManager.GetString("BeamMX_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bending moment.
        /// </summary>
        internal static string BeamMY {
            get {
                return ResourceManager.GetString("BeamMY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bending moment (My).
        /// </summary>
        internal static string BeamMY_Note {
            get {
                return ResourceManager.GetString("BeamMY_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lateral bending moment.
        /// </summary>
        internal static string BeamMZ {
            get {
                return ResourceManager.GetString("BeamMZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lateral bending moment (Mz).
        /// </summary>
        internal static string BeamMZ_Note {
            get {
                return ResourceManager.GetString("BeamMZ_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buckling.
        /// </summary>
        internal static string Buckling {
            get {
                return ResourceManager.GetString("Buckling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buckling in Y direction.
        /// </summary>
        internal static string BucklingDirectionY {
            get {
                return ResourceManager.GetString("BucklingDirectionY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buckling in Z direction.
        /// </summary>
        internal static string BucklingDirectionZ {
            get {
                return ResourceManager.GetString("BucklingDirectionZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation points for linear elements.
        /// </summary>
        internal static string CalcPointSelector {
            get {
                return ResourceManager.GetString("CalcPointSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculating.
        /// </summary>
        internal static string Calculation {
            get {
                return ResourceManager.GetString("Calculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation parameters.
        /// </summary>
        internal static string CalculationOptions {
            get {
                return ResourceManager.GetString("CalculationOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axial load.
        /// </summary>
        internal static string ColumnFX {
            get {
                return ResourceManager.GetString("ColumnFX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axial load (Fx).
        /// </summary>
        internal static string ColumnFX_Note {
            get {
                return ResourceManager.GetString("ColumnFX_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shear force.
        /// </summary>
        internal static string ColumnFY {
            get {
                return ResourceManager.GetString("ColumnFY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shear force (Fy).
        /// </summary>
        internal static string ColumnFY_Note {
            get {
                return ResourceManager.GetString("ColumnFY_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shear force.
        /// </summary>
        internal static string ColumnFZ {
            get {
                return ResourceManager.GetString("ColumnFZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shear force (Fz).
        /// </summary>
        internal static string ColumnFZ_Note {
            get {
                return ResourceManager.GetString("ColumnFZ_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torsional moment.
        /// </summary>
        internal static string ColumnMX {
            get {
                return ResourceManager.GetString("ColumnMX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torsional moment (Mx).
        /// </summary>
        internal static string ColumnMX_Note {
            get {
                return ResourceManager.GetString("ColumnMX_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bending moment.
        /// </summary>
        internal static string ColumnMY {
            get {
                return ResourceManager.GetString("ColumnMY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bending moment (My).
        /// </summary>
        internal static string ColumnMY_Note {
            get {
                return ResourceManager.GetString("ColumnMY_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bending moment.
        /// </summary>
        internal static string ColumnMZ {
            get {
                return ResourceManager.GetString("ColumnMZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bending moment (Mz).
        /// </summary>
        internal static string ColumnMZ_Note {
            get {
                return ResourceManager.GetString("ColumnMZ_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structure.
        /// </summary>
        internal static string ColumnStructureType {
            get {
                return ResourceManager.GetString("ColumnStructureType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creep coefficient.
        /// </summary>
        internal static string CreepCoefficient {
            get {
                return ResourceManager.GetString("CreepCoefficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result package.
        /// </summary>
        internal static string CurrentPackageName {
            get {
                return ResourceManager.GetString("CurrentPackageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing data.
        /// </summary>
        internal static string DataPreparation {
            get {
                return ResourceManager.GetString("DataPreparation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving data.
        /// </summary>
        internal static string DataSaving {
            get {
                return ResourceManager.GetString("DataSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deflection.
        /// </summary>
        internal static string Deflection {
            get {
                return ResourceManager.GetString("Deflection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deflection envelope.
        /// </summary>
        internal static string DeflectionEnvelope {
            get {
                return ResourceManager.GetString("DeflectionEnvelope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deformation.
        /// </summary>
        internal static string DeformationType {
            get {
                return ResourceManager.GetString("DeformationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main direction.
        /// </summary>
        internal static string DimensioningDirectionXFloor {
            get {
                return ResourceManager.GetString("DimensioningDirectionXFloor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical direction.
        /// </summary>
        internal static string DimensioningDirectionXWall {
            get {
                return ResourceManager.GetString("DimensioningDirectionXWall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary direction.
        /// </summary>
        internal static string DimensioningDirectionYFloor {
            get {
                return ResourceManager.GetString("DimensioningDirectionYFloor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal direction.
        /// </summary>
        internal static string DimensioningDirectionYWall {
            get {
                return ResourceManager.GetString("DimensioningDirectionYWall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displacement.
        /// </summary>
        internal static string Displacement {
            get {
                return ResourceManager.GetString("Displacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displacement envelope.
        /// </summary>
        internal static string DisplacementEnvelope {
            get {
                return ResourceManager.GetString("DisplacementEnvelope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division type.
        /// </summary>
        internal static string ElementDivisionType {
            get {
                return ResourceManager.GetString("ElementDivisionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation for.
        /// </summary>
        internal static string EnabledInternalForces {
            get {
                return ResourceManager.GetString("EnabledInternalForces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envelope of axial forces.
        /// </summary>
        internal static string EnvelopeF {
            get {
                return ResourceManager.GetString("EnvelopeF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envelope of bending moments.
        /// </summary>
        internal static string EnvelopeM {
            get {
                return ResourceManager.GetString("EnvelopeM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Materials: Concrete compression is not properly defined..
        /// </summary>
        internal static string ErrConcreteCompression {
            get {
                return ResourceManager.GetString("ErrConcreteCompression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebar Cover: Cover is not properly defined..
        /// </summary>
        internal static string ErrCover {
            get {
                return ResourceManager.GetString("ErrCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element Settings: No internal forces are selected..
        /// </summary>
        internal static string ErrNoChosenInternalForces {
            get {
                return ResourceManager.GetString("ErrNoChosenInternalForces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element Settings: No bars are selected for longitudinal rebar..
        /// </summary>
        internal static string ErrRebarL {
            get {
                return ResourceManager.GetString("ErrRebarL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element Settings: No bars are selected for transverse rebar..
        /// </summary>
        internal static string ErrRebarT {
            get {
                return ResourceManager.GetString("ErrRebarT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element Settings: Incorrect material type is selected for longitudinal rebar..
        /// </summary>
        internal static string ErrReinforcementMaterialL {
            get {
                return ResourceManager.GetString("ErrReinforcementMaterialL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element Settings: Incorrect material type is selected for transverse rebar..
        /// </summary>
        internal static string ErrReinforcementMaterialT {
            get {
                return ResourceManager.GetString("ErrReinforcementMaterialT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element Settings: Minimum yield stress is not properly defined for longitudinal rebar..
        /// </summary>
        internal static string ErrReinforcementYieldStressL {
            get {
                return ResourceManager.GetString("ErrReinforcementYieldStressL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element Settings: Minimum yield stress is not properly defined for transverse rebar..
        /// </summary>
        internal static string ErrReinforcementYieldStressT {
            get {
                return ResourceManager.GetString("ErrReinforcementYieldStressT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types: Element cross section is not supported by this code..
        /// </summary>
        internal static string ErrSectionNotSupported {
            get {
                return ResourceManager.GetString("ErrSectionNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Settings: Input package does not contain static results for the element..
        /// </summary>
        internal static string ErrStaticResults {
            get {
                return ResourceManager.GetString("ErrStaticResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Materials: Young’s Modulus is not properly defined..
        /// </summary>
        internal static string ErrYoungModulus {
            get {
                return ResourceManager.GetString("ErrYoungModulus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extreme values of axial forces.
        /// </summary>
        internal static string ExtremeAxialForces {
            get {
                return ResourceManager.GetString("ExtremeAxialForces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extreme values of bending moments.
        /// </summary>
        internal static string ExtremeBendingMoments {
            get {
                return ResourceManager.GetString("ExtremeBendingMoments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extreme values of reinforcement.
        /// </summary>
        internal static string ExtremeValuesOfReinforcement {
            get {
                return ResourceManager.GetString("ExtremeValuesOfReinforcement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary bottom.
        /// </summary>
        internal static string FloorAxxBottom {
            get {
                return ResourceManager.GetString("FloorAxxBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary top.
        /// </summary>
        internal static string FloorAxxTop {
            get {
                return ResourceManager.GetString("FloorAxxTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary bottom.
        /// </summary>
        internal static string FloorAyyBottom {
            get {
                return ResourceManager.GetString("FloorAyyBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary top.
        /// </summary>
        internal static string FloorAyyTop {
            get {
                return ResourceManager.GetString("FloorAyyTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axial load  (Fxx/Fyy).
        /// </summary>
        internal static string FloorF {
            get {
                return ResourceManager.GetString("FloorF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axial load (Fxx/Fyy).
        /// </summary>
        internal static string FloorF_Note {
            get {
                return ResourceManager.GetString("FloorF_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bending moment (Mxx/Myy).
        /// </summary>
        internal static string FloorM {
            get {
                return ResourceManager.GetString("FloorM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bending moment (Mxx/Myy).
        /// </summary>
        internal static string FloorM_Note {
            get {
                return ResourceManager.GetString("FloorM_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shear force (Fzz).
        /// </summary>
        internal static string FloorQ {
            get {
                return ResourceManager.GetString("FloorQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shear force (Fzz).
        /// </summary>
        internal static string FloorQ_Note {
            get {
                return ResourceManager.GetString("FloorQ_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fx envelope (Max).
        /// </summary>
        internal static string FxMax {
            get {
                return ResourceManager.GetString("FxMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fx envelope (Min).
        /// </summary>
        internal static string FxMin {
            get {
                return ResourceManager.GetString("FxMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fxx (Max).
        /// </summary>
        internal static string FxxMax {
            get {
                return ResourceManager.GetString("FxxMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fxx (Min).
        /// </summary>
        internal static string FxxMin {
            get {
                return ResourceManager.GetString("FxxMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fy envelope (Max).
        /// </summary>
        internal static string FyMax {
            get {
                return ResourceManager.GetString("FyMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fy envelope (Min).
        /// </summary>
        internal static string FyMin {
            get {
                return ResourceManager.GetString("FyMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fyy (Max).
        /// </summary>
        internal static string FyyMax {
            get {
                return ResourceManager.GetString("FyyMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fyy (Min).
        /// </summary>
        internal static string FyyMin {
            get {
                return ResourceManager.GetString("FyyMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fz envelope (Max).
        /// </summary>
        internal static string FzMax {
            get {
                return ResourceManager.GetString("FzMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fz envelope (Min).
        /// </summary>
        internal static string FzMin {
            get {
                return ResourceManager.GetString("FzMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal reinforcement.
        /// </summary>
        internal static string HorizontalReinforcement {
            get {
                return ResourceManager.GetString("HorizontalReinforcement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal reinforcement.
        /// </summary>
        internal static string HorizontalRnfSteelParameters {
            get {
                return ResourceManager.GetString("HorizontalRnfSteelParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal force envelopes.
        /// </summary>
        internal static string Internal_Forces {
            get {
                return ResourceManager.GetString("Internal_Forces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal moment envelopes.
        /// </summary>
        internal static string Internal_Moments {
            get {
                return ResourceManager.GetString("Internal_Moments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal forces.
        /// </summary>
        internal static string InternalForces {
            get {
                return ResourceManager.GetString("InternalForces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add points at maximum calculated forces.
        /// </summary>
        internal static string IsPointsOfExtremeValues {
            get {
                return ResourceManager.GetString("IsPointsOfExtremeValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layers.
        /// </summary>
        internal static string Layers {
            get {
                return ResourceManager.GetString("Layers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element consist with more then one layer. The Layer taken into consideration in the calculation:.
        /// </summary>
        internal static string LayerTakenIntoConsideration {
            get {
                return ResourceManager.GetString("LayerTakenIntoConsideration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length coefficient Y.
        /// </summary>
        internal static string LengthCoefficientY {
            get {
                return ResourceManager.GetString("LengthCoefficientY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length coefficient Z.
        /// </summary>
        internal static string LengthCoefficientZ {
            get {
                return ResourceManager.GetString("LengthCoefficientZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load cases.
        /// </summary>
        internal static string LoadCases {
            get {
                return ResourceManager.GetString("LoadCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load combinations.
        /// </summary>
        internal static string LoadCombinations {
            get {
                return ResourceManager.GetString("LoadCombinations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loads cases and combinations.
        /// </summary>
        internal static string LoadsAndCombinations {
            get {
                return ResourceManager.GetString("LoadsAndCombinations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitudinal reinforcement charts.
        /// </summary>
        internal static string Long_Reinforcement {
            get {
                return ResourceManager.GetString("Long_Reinforcement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitudinal reinforcement.
        /// </summary>
        internal static string LongitudinalReinforcement {
            get {
                return ResourceManager.GetString("LongitudinalReinforcement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom longitudinal reinforcement.
        /// </summary>
        internal static string LongReinforcementBottom {
            get {
                return ResourceManager.GetString("LongReinforcementBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left longitudinal reinforcement.
        /// </summary>
        internal static string LongReinforcementLeft {
            get {
                return ResourceManager.GetString("LongReinforcementLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right longitudinal reinforcement.
        /// </summary>
        internal static string LongReinforcementRight {
            get {
                return ResourceManager.GetString("LongReinforcementRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top longitudinal reinforcement.
        /// </summary>
        internal static string LongReinforcementTop {
            get {
                return ResourceManager.GetString("LongReinforcementTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material.
        /// </summary>
        internal static string Material {
            get {
                return ResourceManager.GetString("Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum longitudinal reinforcement.
        /// </summary>
        internal static string MaximumLongitudinalReinforcement {
            get {
                return ResourceManager.GetString("MaximumLongitudinalReinforcement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum stirrups spacing.
        /// </summary>
        internal static string MaximumStirrupsSpacing {
            get {
                return ResourceManager.GetString("MaximumStirrupsSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mean horizontal reinforcement density.
        /// </summary>
        internal static string MeanHorizontalReinforcementDensity {
            get {
                return ResourceManager.GetString("MeanHorizontalReinforcementDensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mean primary reinforcement density.
        /// </summary>
        internal static string MeanPrimaryReinforcementDensity {
            get {
                return ResourceManager.GetString("MeanPrimaryReinforcementDensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mean longitudinal reinforcement density.
        /// </summary>
        internal static string MeanReinforcemenDensityLongitudinal {
            get {
                return ResourceManager.GetString("MeanReinforcemenDensityLongitudinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mean secondary reinforcement density.
        /// </summary>
        internal static string MeanSecondaryReinforcementDensity {
            get {
                return ResourceManager.GetString("MeanSecondaryReinforcementDensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mean transverse reinforcement density.
        /// </summary>
        internal static string MeanTransversalReinforcemenDensity {
            get {
                return ResourceManager.GetString("MeanTransversalReinforcemenDensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mean vertical reinforcement density.
        /// </summary>
        internal static string MeanVerticallReinforcementDensity {
            get {
                return ResourceManager.GetString("MeanVerticallReinforcementDensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum longitudinal reinforcement.
        /// </summary>
        internal static string MinimumLongitudinalReinforcement {
            get {
                return ResourceManager.GetString("MinimumLongitudinalReinforcement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum stirrups spacing.
        /// </summary>
        internal static string MinimumStirrupsSpacing {
            get {
                return ResourceManager.GetString("MinimumStirrupsSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum yield stress.
        /// </summary>
        internal static string MinimumYieldStress {
            get {
                return ResourceManager.GetString("MinimumYieldStress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mx envelope (Max).
        /// </summary>
        internal static string MxMax {
            get {
                return ResourceManager.GetString("MxMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mx envelope (Min).
        /// </summary>
        internal static string MxMin {
            get {
                return ResourceManager.GetString("MxMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mxx (Max).
        /// </summary>
        internal static string MxxMax {
            get {
                return ResourceManager.GetString("MxxMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mxx (Min).
        /// </summary>
        internal static string MxxMin {
            get {
                return ResourceManager.GetString("MxxMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My envelope (Max).
        /// </summary>
        internal static string MyMax {
            get {
                return ResourceManager.GetString("MyMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My envelope (Min).
        /// </summary>
        internal static string MyMin {
            get {
                return ResourceManager.GetString("MyMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Myy (Max).
        /// </summary>
        internal static string MyyMax {
            get {
                return ResourceManager.GetString("MyyMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Myy (Min).
        /// </summary>
        internal static string MyyMin {
            get {
                return ResourceManager.GetString("MyyMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mz envelope (Max).
        /// </summary>
        internal static string MzMax {
            get {
                return ResourceManager.GetString("MzMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mz envelope (Min).
        /// </summary>
        internal static string MzMin {
            get {
                return ResourceManager.GetString("MzMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None selected.
        /// </summary>
        internal static string NoneSelected {
            get {
                return ResourceManager.GetString("NoneSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-sway.
        /// </summary>
        internal static string NonSway {
            get {
                return ResourceManager.GetString("NonSway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not taken into consideration.
        /// </summary>
        internal static string NotTakenIntoConsideration {
            get {
                return ResourceManager.GetString("NotTakenIntoConsideration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constant number of points.
        /// </summary>
        internal static string Points {
            get {
                return ResourceManager.GetString("Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary reinforcement.
        /// </summary>
        internal static string PrimaryReinforcement {
            get {
                return ResourceManager.GetString("PrimaryReinforcement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary reinforcement.
        /// </summary>
        internal static string PrimaryRnfSteelParameters {
            get {
                return ResourceManager.GetString("PrimaryRnfSteelParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading geometry.
        /// </summary>
        internal static string ReadingGeometry {
            get {
                return ResourceManager.GetString("ReadingGeometry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RC deflection.
        /// </summary>
        internal static string Real___Deflection {
            get {
                return ResourceManager.GetString("Real___Deflection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebar bar.
        /// </summary>
        internal static string RebarBarType {
            get {
                return ResourceManager.GetString("RebarBarType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reinforcement.
        /// </summary>
        internal static string Reinforcement {
            get {
                return ResourceManager.GetString("Reinforcement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reinforcement maps.
        /// </summary>
        internal static string ReinforcementMaps {
            get {
                return ResourceManager.GetString("ReinforcementMaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary reinforcement.
        /// </summary>
        internal static string SecondaryReinforcement {
            get {
                return ResourceManager.GetString("SecondaryReinforcement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary reinforcement.
        /// </summary>
        internal static string SecondaryRnfSteelParameters {
            get {
                return ResourceManager.GetString("SecondaryRnfSteelParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section at distance.
        /// </summary>
        internal static string SectionAtDistance {
            get {
                return ResourceManager.GetString("SectionAtDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constant segment length.
        /// </summary>
        internal static string Segments {
            get {
                return ResourceManager.GetString("Segments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slab-beam interaction.
        /// </summary>
        internal static string SlabBeamInteraction {
            get {
                return ResourceManager.GetString("SlabBeamInteraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stirrups spacing.
        /// </summary>
        internal static string StirrupsSpacing {
            get {
                return ResourceManager.GetString("StirrupsSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        internal static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sway.
        /// </summary>
        internal static string Sway {
            get {
                return ResourceManager.GetString("Sway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thickness taken into consideration in the calculation.
        /// </summary>
        internal static string ThicknessTakenIntoConsideration {
            get {
                return ResourceManager.GetString("ThicknessTakenIntoConsideration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transverse reinforcement.
        /// </summary>
        internal static string Trans_Reinforcement {
            get {
                return ResourceManager.GetString("Trans_Reinforcement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transverse density.
        /// </summary>
        internal static string TransversalReinforcemenDensity {
            get {
                return ResourceManager.GetString("TransversalReinforcemenDensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transverse reinforcement.
        /// </summary>
        internal static string TransversalReinforcement {
            get {
                return ResourceManager.GetString("TransversalReinforcement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of points.
        /// </summary>
        internal static string UniformDistribution {
            get {
                return ResourceManager.GetString("UniformDistribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the internal forces.
        /// </summary>
        internal static string UseForcesType {
            get {
                return ResourceManager.GetString("UseForcesType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segment length.
        /// </summary>
        internal static string UserSegmentDivision {
            get {
                return ResourceManager.GetString("UserSegmentDivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ux displacement envelope (Max).
        /// </summary>
        internal static string UxMax {
            get {
                return ResourceManager.GetString("UxMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ux displacement envelope (Min).
        /// </summary>
        internal static string UxMin {
            get {
                return ResourceManager.GetString("UxMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fx deflection envelope (Max).
        /// </summary>
        internal static string UxRealMax {
            get {
                return ResourceManager.GetString("UxRealMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fx deflection envelope (Min).
        /// </summary>
        internal static string UxRealMin {
            get {
                return ResourceManager.GetString("UxRealMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uy displacement envelope (Max).
        /// </summary>
        internal static string UyMax {
            get {
                return ResourceManager.GetString("UyMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uy displacement envelope (Min).
        /// </summary>
        internal static string UyMin {
            get {
                return ResourceManager.GetString("UyMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fy deflection envelope (Max).
        /// </summary>
        internal static string UyRealMax {
            get {
                return ResourceManager.GetString("UyRealMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fy deflection envelope (Min).
        /// </summary>
        internal static string UyRealMin {
            get {
                return ResourceManager.GetString("UyRealMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uz displacement envelope (Max).
        /// </summary>
        internal static string UzMax {
            get {
                return ResourceManager.GetString("UzMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uz displacement envelope (Min).
        /// </summary>
        internal static string UzMin {
            get {
                return ResourceManager.GetString("UzMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fz deflection envelope (Max).
        /// </summary>
        internal static string UzRealMax {
            get {
                return ResourceManager.GetString("UzRealMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fz deflection envelope (Min).
        /// </summary>
        internal static string UzRealMin {
            get {
                return ResourceManager.GetString("UzRealMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical reinforcement.
        /// </summary>
        internal static string VerticalReinforcement {
            get {
                return ResourceManager.GetString("VerticalReinforcement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical reinforcement.
        /// </summary>
        internal static string VerticalRnfSteelParameters {
            get {
                return ResourceManager.GetString("VerticalRnfSteelParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical internal.
        /// </summary>
        internal static string WallAxxBottom {
            get {
                return ResourceManager.GetString("WallAxxBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical external.
        /// </summary>
        internal static string WallAxxTop {
            get {
                return ResourceManager.GetString("WallAxxTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal internal.
        /// </summary>
        internal static string WallAyyBottom {
            get {
                return ResourceManager.GetString("WallAyyBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal external.
        /// </summary>
        internal static string WallAyyTop {
            get {
                return ResourceManager.GetString("WallAyyTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axial load (Fxx/Fyy).
        /// </summary>
        internal static string WallF {
            get {
                return ResourceManager.GetString("WallF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axial load (Fxx/Fyy).
        /// </summary>
        internal static string WallF_Note {
            get {
                return ResourceManager.GetString("WallF_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bending moment (Mxx/Myy).
        /// </summary>
        internal static string WallM {
            get {
                return ResourceManager.GetString("WallM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bending moment (Mxx/Myy).
        /// </summary>
        internal static string WallM_Note {
            get {
                return ResourceManager.GetString("WallM_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shear force (Fzz).
        /// </summary>
        internal static string WallQ {
            get {
                return ResourceManager.GetString("WallQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shear force (Fzz).
        /// </summary>
        internal static string WallQ_Note {
            get {
                return ResourceManager.GetString("WallQ_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        internal static string X {
            get {
                return ResourceManager.GetString("X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        internal static string X_ {
            get {
                return ResourceManager.GetString("X_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relative distance.
        /// </summary>
        internal static string X_Rel {
            get {
                return ResourceManager.GetString("X_Rel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y.
        /// </summary>
        internal static string Y {
            get {
                return ResourceManager.GetString("Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z.
        /// </summary>
        internal static string Z {
            get {
                return ResourceManager.GetString("Z", resourceCulture);
            }
        }
    }
}
