// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "pch.h"
#include "astweldcontrol.h"

/////////////////////////////////////////////////////////////////////////////
// CAstWeldControl

IMPLEMENT_DYNCREATE(CAstWeldControl, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CAstWeldControl properties

/////////////////////////////////////////////////////////////////////////////
// CAstWeldControl operations
