//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Revit.SDK.Samples.CurtainSystem.CS.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Revit.SDK.Samples.CurtainSystem.CS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _new {
            get {
                object obj = ResourceManager.GetObject("new", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete {
            get {
                object obj = ResourceManager.GetObject("delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No curtain system available. Please create some first..
        /// </summary>
        internal static string HINT_CreateCSFirst {
            get {
                return ResourceManager.GetString("HINT_CreateCSFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by face array, forbidden to add/remove curtain grids..
        /// </summary>
        internal static string HINT_CSIsByFaceArray {
            get {
                return ResourceManager.GetString("HINT_CSIsByFaceArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curtain system must have at least one curtain grid..
        /// </summary>
        internal static string HINT_KeepOneCG {
            get {
                return ResourceManager.GetString("HINT_KeepOneCG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select some curtain grids and make them checked first..
        /// </summary>
        internal static string HINT_SelectCGFirst {
            get {
                return ResourceManager.GetString("HINT_SelectCGFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select some curtain systems and make them checked first..
        /// </summary>
        internal static string HINT_SelectCSFirst {
            get {
                return ResourceManager.GetString("HINT_SelectCSFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select some uncovered faces and make them checked first..
        /// </summary>
        internal static string HINT_SelectFaceFirst {
            get {
                return ResourceManager.GetString("HINT_SelectFaceFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error! Add curtain grid to the mass failed. The application will be terminated..
        /// </summary>
        internal static string MSG_AddCGFailed {
            get {
                return ResourceManager.GetString("MSG_AddCGFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error! Create curtain system failed. The application will be terminated..
        /// </summary>
        internal static string MSG_CreateCSFailed {
            get {
                return ResourceManager.GetString("MSG_CreateCSFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error! Please select a parallelepiped mass first. The application will be terminated..
        /// </summary>
        internal static string MSG_InvalidSelection {
            get {
                return ResourceManager.GetString("MSG_InvalidSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal Error! More than 1 curtain system was created. The application will be terminated..
        /// </summary>
        internal static string MSG_MoreThan1CSCreated {
            get {
                return ResourceManager.GetString("MSG_MoreThan1CSCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error! Remove curtain grid failed. The application will be terminated..
        /// </summary>
        internal static string MSG_RemoveCGFailed {
            get {
                return ResourceManager.GetString("MSG_RemoveCGFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curtain System.
        /// </summary>
        internal static string TXT_DialogTitle {
            get {
                return ResourceManager.GetString("TXT_DialogTitle", resourceCulture);
            }
        }
    }
}
