#if !defined(AFX_ASTCOMBOTABLECONTROL_H__F0089DE6_AC5E_4C13_A7BD_EBCAF601FDB0__INCLUDED_)
#define AFX_ASTCOMBOTABLECONTROL_H__F0089DE6_AC5E_4C13_A7BD_EBCAF601FDB0__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.
/////////////////////////////////////////////////////////////////////////////
// CAstComboTableControl wrapper class

class CAstComboTableControl : public CWnd
{
protected:
	DECLARE_DYNCREATE(CAstComboTableControl)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xfeaa9dcf, 0x65c5, 0x4650, { 0xb5, 0xcb, 0xb1, 0xa9, 0x14, 0xb6, 0x19, 0xfe } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	CString GetTableName();
	void SetTableName(LPCTSTR);
	void SetDSNTableName(CString);
	long GetComboIndex();
	void SetComboIndex(long);
	CString GetComboCaption();
	void SetComboCaption(LPCTSTR);
	long GetLabelLength();
	void SetLabelLength(long);
	long GetLabelKey();
	void SetLabelKey(long);
	BOOL GetSort();
	void SetSort(BOOL);
	BOOL GetEnabled();
	void SetEnabled(BOOL);
	long GetLongKey();
	void SetLongKey(long);
	double GetDoubleKey();
	void SetDoubleKey(double);
	CString GetStringKey();
	void SetStringKey(LPCTSTR);

// Operations
public:
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_ASTCOMBOTABLECONTROL_H__F0089DE6_AC5E_4C13_A7BD_EBCAF601FDB0__INCLUDED_)
