#pragma once

// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.
/////////////////////////////////////////////////////////////////////////////
// CAstStaticTextControl wrapper class

class CAstStaticTextControl : public CWnd
{
protected:
	DECLARE_DYNCREATE(CAstStaticTextControl)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x25D0C857, 0x2689, 0x481C, { 0xB4, 0x70, 0xA0, 0x62, 0xE5, 0x9, 0x9, 0x58 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName, LPCTSTR lpszWindowName, DWORD dwStyle,
						const RECT& rect, CWnd* pParentWnd, UINT nID, 
						CCreateContext* pContext = NULL)
	{ 
		return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); 
	}

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle, const RECT& rect, CWnd* pParentWnd, 
				UINT nID, CFile* pPersist = NULL, BOOL bStorage = FALSE,
				BSTR bstrLicKey = NULL)
	{ 
		return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); 
	}

// Attributes
public:
enum
{
    kEditBox = 0,
    kListBox = 1,
    kComboBox = 2,
    kCheckBox = 3,
    kProfileEdit = 4,
    kButton = 5
}eColumnType;
enum
{
    kUnits = 0,
    kDouble = 1,
    kInteger = 2,
    kString = 3
}eColumnDataType;
enum
{
    kUnitDistance = 0,
    kUnitAngle = 1,
    kUnitWeight = 2,
    kUnitDistanceGUI = 3,
    kUnitArea = 4,
    kUnitVolume = 5,
    kUnitForce = 6,
    kUnitMoment = 7
}eColumnUnitType;
enum
{
    kBeam = 1,
    kPlate = 2
}eGroupingRole;
enum
{
    kGratingStandard = 0,
    kGratingVariable = 1
}eGratingType;
enum
{
    kType = 0,
    kClass = 1,
    kSize = 2
}eGratingControls;
enum
{
    kNull = 0,
    kAnglePage = 1,
    kAreaPage = 2,
    kWeightPage = 4,
    kLengthPage = 8,
    kWeightPerDistancePage = 16,
    kAllPages = 255
}eFirstPage;


// Operations
public:

// _DAstStaticPrompt

// Functions
//


// Properties
//

long GetKey()
{
	long result;
	GetProperty(0x1, VT_I4, (void*)&result);
	return result;
}
void SetKey(long propVal)
{
	SetProperty(0x1, VT_I4, propVal);
}
BOOL GetEnabled()
{
	BOOL result;
	GetProperty(DISPID_ENABLED, VT_BOOL, (void*)&result);
	return result;
}
void SetEnabled(BOOL propVal)
{
	SetProperty(DISPID_ENABLED, VT_BOOL, propVal);
}


};
