// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "pch.h"
#include "boltstandards.h"

/////////////////////////////////////////////////////////////////////////////
// CBoltstandardsctrl1

IMPLEMENT_DYNCREATE(CBoltStandards, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CBoltstandardsctrl1 properties

/////////////////////////////////////////////////////////////////////////////
// CBoltstandardsctrl1 operations
