//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REX.DRevitFreezeDrawing.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("REX.DRevitFreezeDrawing.Resources.Strings.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACIS.
        /// </summary>
        internal static string Acis {
            get {
                return ResourceManager.GetString("Acis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIA.
        /// </summary>
        internal static string AIA {
            get {
                return ResourceManager.GetString("AIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BS1192.
        /// </summary>
        internal static string BS1192 {
            get {
                return ResourceManager.GetString("BS1192", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Entity.
        /// </summary>
        internal static string ByEntity {
            get {
                return ResourceManager.GetString("ByEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Layer.
        /// </summary>
        internal static string ByLayer {
            get {
                return ResourceManager.GetString("ByLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centimeter.
        /// </summary>
        internal static string Centimeter {
            get {
                return ResourceManager.GetString("Centimeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the folder where files will be copied.
        /// </summary>
        internal static string ChooseFolder {
            get {
                return ResourceManager.GetString("ChooseFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy DWG files to directory.
        /// </summary>
        internal static string CopyDwgFiles {
            get {
                return ResourceManager.GetString("CopyDwgFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying.
        /// </summary>
        internal static string Copying {
            get {
                return ResourceManager.GetString("Copying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CP38.
        /// </summary>
        internal static string CP38 {
            get {
                return ResourceManager.GetString("CP38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current view.
        /// </summary>
        internal static string CurrentView {
            get {
                return ResourceManager.GetString("CurrentView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current view can&apos;t be frozen. Do you want to continue?.
        /// </summary>
        internal static string CurrentViewNotSet {
            get {
                return ResourceManager.GetString("CurrentViewNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string DwgVersion {
            get {
                return ResourceManager.GetString("DwgVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied on file: .
        /// </summary>
        internal static string ErrorAccessDenied {
            get {
                return ResourceManager.GetString("ErrorAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - copy failed.
        /// </summary>
        internal static string ErrorCopyFailed {
            get {
                return ResourceManager.GetString("ErrorCopyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No selected views. Do you want to continue?.
        /// </summary>
        internal static string ErrorNoViewsDetected {
            get {
                return ResourceManager.GetString("ErrorNoViewsDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        internal static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foot.
        /// </summary>
        internal static string Foot {
            get {
                return ResourceManager.GetString("Foot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frozen.
        /// </summary>
        internal static string Freezed {
            get {
                return ResourceManager.GetString("Freezed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freezing in progress.
        /// </summary>
        internal static string FreezeInProgress {
            get {
                return ResourceManager.GetString("FreezeInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Freeze operation is completed successfully. Go to &apos;Drafting views&apos;  to see the drawings..
        /// </summary>
        internal static string FreezingFinSuccesfull {
            get {
                return ResourceManager.GetString("FreezingFinSuccesfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inch.
        /// </summary>
        internal static string Inch {
            get {
                return ResourceManager.GetString("Inch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISO13567.
        /// </summary>
        internal static string ISO13567 {
            get {
                return ResourceManager.GetString("ISO13567", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        internal static string MessageBox_CaptionQuestion {
            get {
                return ResourceManager.GetString("MessageBox_CaptionQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors occurred! Do you want to continue?.
        /// </summary>
        internal static string MessageBox_ErrorQuestion {
            get {
                return ResourceManager.GetString("MessageBox_ErrorQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meter.
        /// </summary>
        internal static string Meter {
            get {
                return ResourceManager.GetString("Meter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Millimeter.
        /// </summary>
        internal static string Milimiter {
            get {
                return ResourceManager.GetString("Milimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model space.
        /// </summary>
        internal static string ModelSpace {
            get {
                return ResourceManager.GetString("ModelSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Layer.
        /// </summary>
        internal static string NewLayer {
            get {
                return ResourceManager.GetString("NewLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No selected views.
        /// </summary>
        internal static string NoViewsSelected {
            get {
                return ResourceManager.GetString("NoViewsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paper space.
        /// </summary>
        internal static string PaperSpace {
            get {
                return ResourceManager.GetString("PaperSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polymesh.
        /// </summary>
        internal static string Polymesh {
            get {
                return ResourceManager.GetString("Polymesh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project internal.
        /// </summary>
        internal static string ProjectInternal {
            get {
                return ResourceManager.GetString("ProjectInternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freeze drawings.
        /// </summary>
        internal static string REX_ModuleDescription {
            get {
                return ResourceManager.GetString("REX_ModuleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared.
        /// </summary>
        internal static string Shared {
            get {
                return ResourceManager.GetString("Shared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheets.
        /// </summary>
        internal static string Sheets {
            get {
                return ResourceManager.GetString("Sheets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        internal static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        internal static string Skip {
            get {
                return ResourceManager.GetString("Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip all.
        /// </summary>
        internal static string SkipAll {
            get {
                return ResourceManager.GetString("SkipAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solids.
        /// </summary>
        internal static string Solids {
            get {
                return ResourceManager.GetString("Solids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Views.
        /// </summary>
        internal static string Views {
            get {
                return ResourceManager.GetString("Views", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Scale.
        /// </summary>
        internal static string ViewScale {
            get {
                return ResourceManager.GetString("ViewScale", resourceCulture);
            }
        }
    }
}
