// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

#include "pch.h"
#include "astbitmapcontrol.h"
/////////////////////////////////////////////////////////////////////////////
// CAstBitmapControl

IMPLEMENT_DYNCREATE(CAstBitmapControl, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CAstBitmapControl properties

long CAstBitmapControl::GetKey()
{
	long result;
	GetProperty(0x1, VT_I4, (void*)&result);
	return result;
}

void CAstBitmapControl::SetKey(long propVal)
{
	SetProperty(0x1, VT_I4, propVal);
}

BOOL CAstBitmapControl::GetEnabled()
{
	BOOL result;
	GetProperty(DISPID_ENABLED, VT_BOOL, (void*)&result);
	return result;
}

void CAstBitmapControl::SetEnabled(BOOL propVal)
{
	SetProperty(DISPID_ENABLED, VT_BOOL, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CAstBitmapControl operations
