// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "pch.h"
#include "astcombotablecontrol.h"

/////////////////////////////////////////////////////////////////////////////
// CAstComboTableControl

IMPLEMENT_DYNCREATE(CAstComboTableControl, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CAstComboTableControl properties

CString CAstComboTableControl::GetTableName()
{
	CString result;
	GetProperty(0x1, VT_BSTR, (void*)&result);
	return result;
}

void CAstComboTableControl::SetTableName(LPCTSTR propVal)
{	
	SetProperty(0x1, VT_BSTR, propVal);
}

void CAstComboTableControl::SetDSNTableName(CString strDSN)
{
	CString strDSNTableName = GetTableName();
	if (!strDSNTableName.IsEmpty() && strDSNTableName.Find(_T("."))==-1)
	{
		strDSNTableName = CString(strDSN) + CString(L".") + strDSNTableName;
	}
	SetProperty(0x1, VT_BSTR, strDSNTableName.GetString());
}

long CAstComboTableControl::GetComboIndex()
{
	long result;
	GetProperty(0x2, VT_I4, (void*)&result);
	return result;
}

void CAstComboTableControl::SetComboIndex(long propVal)
{
	SetProperty(0x2, VT_I4, propVal);
}

CString CAstComboTableControl::GetComboCaption()
{
	CString result;
	GetProperty(0x3, VT_BSTR, (void*)&result);
	return result;
}

void CAstComboTableControl::SetComboCaption(LPCTSTR propVal)
{
	SetProperty(0x3, VT_BSTR, propVal);
}

long CAstComboTableControl::GetLabelLength()
{
	long result;
	GetProperty(0x4, VT_I4, (void*)&result);
	return result;
}

void CAstComboTableControl::SetLabelLength(long propVal)
{
	SetProperty(0x4, VT_I4, propVal);
}

long CAstComboTableControl::GetLabelKey()
{
	long result;
	GetProperty(0x5, VT_I4, (void*)&result);
	return result;
}

void CAstComboTableControl::SetLabelKey(long propVal)
{
	SetProperty(0x5, VT_I4, propVal);
}

BOOL CAstComboTableControl::GetSort()
{
	BOOL result;
	GetProperty(0x6, VT_BOOL, (void*)&result);
	return result;
}

void CAstComboTableControl::SetSort(BOOL propVal)
{
	SetProperty(0x6, VT_BOOL, propVal);
}

BOOL CAstComboTableControl::GetEnabled()
{
	BOOL result;
	GetProperty(DISPID_ENABLED, VT_BOOL, (void*)&result);
	return result;
}

void CAstComboTableControl::SetEnabled(BOOL propVal)
{
	SetProperty(DISPID_ENABLED, VT_BOOL, propVal);
}

long CAstComboTableControl::GetLongKey()
{
	long result;
	GetProperty(0x7, VT_I4, (void*)&result);
	return result;
}

void CAstComboTableControl::SetLongKey(long propVal)
{
	SetProperty(0x7, VT_I4, propVal);
}

double CAstComboTableControl::GetDoubleKey()
{
	double result;
	GetProperty(0x8, VT_R8, (void*)&result);
	return result;
}

void CAstComboTableControl::SetDoubleKey(double propVal)
{
	SetProperty(0x8, VT_R8, propVal);
}

CString CAstComboTableControl::GetStringKey()
{
	CString result;
	GetProperty(0x9, VT_BSTR, (void*)&result);
	return result;
}

void CAstComboTableControl::SetStringKey(LPCTSTR propVal)
{
	SetProperty(0x9, VT_BSTR, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CAstComboTableControl operations
