// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "pch.h"
#include "astcheckboxcontrol.h"

/////////////////////////////////////////////////////////////////////////////
// CAstCheckBoxControl

IMPLEMENT_DYNCREATE(CAstCheckBoxControl, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CAstCheckBoxControl properties

long CAstCheckBoxControl::GetCaptionKey()
{
	long result;
	GetProperty(0x1, VT_I4, (void*)&result);
	return result;
}

void CAstCheckBoxControl::SetCaptionKey(long propVal)
{
	SetProperty(0x1, VT_I4, propVal);
}

BOOL CAstCheckBoxControl::GetValue()
{
	BOOL result;
	GetProperty(0x2, VT_BOOL, (void*)&result);
	return result;
}

void CAstCheckBoxControl::SetValue(BOOL propVal)
{
	SetProperty(0x2, VT_BOOL, propVal);
}

BOOL CAstCheckBoxControl::GetEnabled()
{
	BOOL result;
	GetProperty(DISPID_ENABLED, VT_BOOL, (void*)&result);
	return result;
}

void CAstCheckBoxControl::SetEnabled(BOOL propVal)
{
	SetProperty(DISPID_ENABLED, VT_BOOL, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CAstCheckBoxControl operations
