// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "pch.h"
#include "astprofilecontrol.h"

/////////////////////////////////////////////////////////////////////////////
// CAstProfileControl

IMPLEMENT_DYNCREATE(CAstProfileControl, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CAstProfileControl properties

BOOL CAstProfileControl::GetShowHideAllSections()
{
	BOOL result;
	GetProperty(0x1, VT_BOOL, (void*)&result);
	return result;
}

void CAstProfileControl::SetShowHideAllSections(BOOL propVal)
{
	SetProperty(0x1, VT_BOOL, propVal);
}

CString CAstProfileControl::GetCurrentProfileName()
{
	CString result;
	GetProperty(0x2, VT_BSTR, (void*)&result);
	return result;
}

void CAstProfileControl::SetCurrentProfileName(LPCTSTR propVal)
{
	SetProperty(0x2, VT_BSTR, propVal);
}

CString CAstProfileControl::GetCurrentClass()
{
	CString result;
	GetProperty(0x3, VT_BSTR, (void*)&result);
	return result;
}

void CAstProfileControl::SetCurrentClass(LPCTSTR propVal)
{
	SetProperty(0x3, VT_BSTR, propVal);
}

CString CAstProfileControl::GetCurrentSection()
{
	CString result;
	GetProperty(0x4, VT_BSTR, (void*)&result);
	return result;
}

void CAstProfileControl::SetCurrentSection(LPCTSTR propVal)
{
	SetProperty(0x4, VT_BSTR, propVal);
}

long CAstProfileControl::GetCaptionClass()
{
	long result;
	GetProperty(0x5, VT_I4, (void*)&result);
	return result;
}

void CAstProfileControl::SetCaptionClass(long propVal)
{
	SetProperty(0x5, VT_I4, propVal);
}

long CAstProfileControl::GetCaptionTyp()
{
	long result;
	GetProperty(0x6, VT_I4, (void*)&result);
	return result;
}

void CAstProfileControl::SetCaptionTyp(long propVal)
{
	SetProperty(0x6, VT_I4, propVal);
}

long CAstProfileControl::GetCaptionShowHideAllSections()
{
	long result;
	GetProperty(0x7, VT_I4, (void*)&result);
	return result;
}

void CAstProfileControl::SetCaptionShowHideAllSections(long propVal)
{
	SetProperty(0x7, VT_I4, propVal);
}

BOOL CAstProfileControl::GetUseFilterClass()
{
	BOOL result;
	GetProperty(0x8, VT_BOOL, (void*)&result);
	return result;
}

void CAstProfileControl::SetUseFilterClass(BOOL propVal)
{
	SetProperty(0x8, VT_BOOL, propVal);
}

BOOL CAstProfileControl::GetCheckBoxOnLeft()
{
	BOOL result;
	GetProperty(0x9, VT_BOOL, (void*)&result);
	return result;
}

void CAstProfileControl::SetCheckBoxOnLeft(BOOL propVal)
{
	SetProperty(0x9, VT_BOOL, propVal);
}

long CAstProfileControl::GetLabelLength()
{
	long result;
	GetProperty(0xa, VT_I4, (void*)&result);
	return result;
}

void CAstProfileControl::SetLabelLength(long propVal)
{
	SetProperty(0xa, VT_I4, propVal);
}

CString CAstProfileControl::GetCurrentCrossSection()
{
	CString result;
	GetProperty(0xb, VT_BSTR, (void*)&result);
	return result;
}

void CAstProfileControl::SetCurrentCrossSection(LPCTSTR propVal)
{
	SetProperty(0xb, VT_BSTR, propVal);
}

BOOL CAstProfileControl::GetSummaryRepresentation()
{
	BOOL result;
	GetProperty(0xc, VT_BOOL, (void*)&result);
	return result;
}

void CAstProfileControl::SetSummaryRepresentation(BOOL propVal)
{
	SetProperty(0xc, VT_BOOL, propVal);
}

BOOL CAstProfileControl::GetAppearance()
{
	BOOL result;
	GetProperty(0xd, VT_BOOL, (void*)&result);
	return result;
}

void CAstProfileControl::SetAppearance(BOOL propVal)
{
	SetProperty(0xd, VT_BOOL, propVal);
}

long CAstProfileControl::GetDropHeight()
{
	long result;
	GetProperty(0xe, VT_I4, (void*)&result);
	return result;
}

void CAstProfileControl::SetDropHeight(long propVal)
{
	SetProperty(0xe, VT_I4, propVal);
}

long CAstProfileControl::GetDropWidth()
{
	long result;
	GetProperty(0xf, VT_I4, (void*)&result);
	return result;
}

void CAstProfileControl::SetDropWidth(long propVal)
{
	SetProperty(0xf, VT_I4, propVal);
}

BOOL CAstProfileControl::GetSummaryDroppedDown()
{
	BOOL result;
	GetProperty(0x10, VT_BOOL, (void*)&result);
	return result;
}

void CAstProfileControl::SetSummaryDroppedDown(BOOL propVal)
{
	SetProperty(0x10, VT_BOOL, propVal);
}

BOOL CAstProfileControl::GetEnabled()
{
	BOOL result;
	GetProperty(DISPID_ENABLED, VT_BOOL, (void*)&result);
	return result;
}

void CAstProfileControl::SetEnabled(BOOL propVal)
{
	SetProperty(DISPID_ENABLED, VT_BOOL, propVal);
}

BOOL CAstProfileControl::GetShowPromptOnTop()
{
  BOOL result;
  GetProperty(0x17, VT_BOOL, (void*)&result);
  return result;
}

void CAstProfileControl::SetShowPromptOnTop(BOOL propVal)
{
  SetProperty(0x17, VT_BOOL, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CAstProfileControl operations

void CAstProfileControl::AppendAcceptedClass(LPCTSTR newAcceptedClass)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x11, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 newAcceptedClass);
}

void CAstProfileControl::RemoveAcceptedClass(LPCTSTR AcceptedClass)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x12, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 AcceptedClass);
}

void CAstProfileControl::AppendAcceptedClassGroup(LPCTSTR SubtypeName)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x13, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 SubtypeName);
}


void CAstProfileControl::RemoveAcceptedClassGroup(LPCTSTR SubtypeName)
{
  static BYTE parms[] =
    VTS_BSTR;
  InvokeHelper(0x18, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
    SubtypeName);
}

void CAstProfileControl::Reset()
{
  InvokeHelper(0x19, DISPATCH_METHOD, VT_EMPTY, NULL, VTS_NONE);
}
