#if !defined(AFX_ASTSTATICPROMPT_H__02DA9F43_CBBF_49F9_8E53_3B82F1251DA3__INCLUDED_)
#define AFX_ASTSTATICPROMPT_H__02DA9F43_CBBF_49F9_8E53_3B82F1251DA3__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++
// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CAstStaticPrompt wrapper class

class CAstStaticPrompt : public CWnd
{
protected:
	DECLARE_DYNCREATE(CAstStaticPrompt)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x25d0c857, 0x2689, 0x481c, { 0xb4, 0x70, 0xa0, 0x62, 0xe5, 0x9, 0x9, 0x58 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	long GetKey();
	void SetKey(long);
	BOOL GetEnabled();
	void SetEnabled(BOOL);

// Operations
public:
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_ASTSTATICPROMPT_H__02DA9F43_CBBF_49F9_8E53_3B82F1251DA3__INCLUDED_)
