#if !defined(AFX_ASTUNITCONTROL_H__75321BD4_00D6_4705_ABA1_52BD1CE5C48C__INCLUDED_)
#define AFX_ASTUNITCONTROL_H__75321BD4_00D6_4705_ABA1_52BD1CE5C48C__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

// Dispatch interfaces referenced by this interface
class COleFont;
class CUnitsManager;

/////////////////////////////////////////////////////////////////////////////
// CAstUnitControl wrapper class

class CAstUnitControl : public CWnd
{
protected:
	DECLARE_DYNCREATE(CAstUnitControl)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x3a345bcb, 0xe386, 0x45de, { 0xa4, 0x25, 0xf4, 0x51, 0xc6, 0x6e, 0x18, 0x47 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	unsigned long GetBackColor();
	void SetBackColor(unsigned long);
	short GetEditType();
	void SetEditType(short);
	COleFont GetFont();
	void SetFont(LPDISPATCH);
	double GetDoubleValue();
	void SetDoubleValue(double);
	CString GetText();
	void SetText(LPCTSTR);
	CUnitsManager GetUnits();
	void SetUnits(LPDISPATCH);
	long GetLabelDbKey();
	void SetLabelDbKey(long);
	long GetLabelLength();
	void SetLabelLength(long);
	BOOL GetEnabled();
	void SetEnabled(BOOL);
	long GetIntegerValue();
	void SetIntegerValue(long);

// Operations
public:
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_ASTUNITCONTROL_H__75321BD4_00D6_4705_ABA1_52BD1CE5C48C__INCLUDED_)
