// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "pch.h"
#include "unitsmanager.h"


/////////////////////////////////////////////////////////////////////////////
// CUnitsManager properties

/////////////////////////////////////////////////////////////////////////////
// CUnitsManager operations

void CUnitsManager::SetUseRegionalSettings(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x1, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

long CUnitsManager::GetUseRegionalSettings()
{
	long result;
	InvokeHelper(0x1, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void CUnitsManager::getUnitOfDistance(LPDISPATCH retval)
{
	static BYTE parms[] =
		VTS_DISPATCH;
	InvokeHelper(0x2, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 retval);
}

void CUnitsManager::setUnitOfDistance(LPDISPATCH retval)
{
	static BYTE parms[] =
		VTS_DISPATCH;
	InvokeHelper(0x3, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 retval);
}

void CUnitsManager::getUnitOfWeight(LPDISPATCH retval)
{
	static BYTE parms[] =
		VTS_DISPATCH;
	InvokeHelper(0x4, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 retval);
}

void CUnitsManager::setUnitOfWeight(LPDISPATCH retval)
{
	static BYTE parms[] =
		VTS_DISPATCH;
	InvokeHelper(0x5, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 retval);
}

void CUnitsManager::getUnitOfAngle(LPDISPATCH retval)
{
	static BYTE parms[] =
		VTS_DISPATCH;
	InvokeHelper(0x6, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 retval);
}

void CUnitsManager::setUnitOfAngle(LPDISPATCH retval)
{
	static BYTE parms[] =
		VTS_DISPATCH;
	InvokeHelper(0x7, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 retval);
}

void CUnitsManager::doModal()
{
	InvokeHelper(0x8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CUnitsManager::getUnitOfArea(LPDISPATCH retval)
{
	static BYTE parms[] =
		VTS_DISPATCH;
	InvokeHelper(0x9, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 retval);
}

void CUnitsManager::setUnitOfArea(LPDISPATCH retval)
{
	static BYTE parms[] =
		VTS_DISPATCH;
	InvokeHelper(0xa, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 retval);
}

void CUnitsManager::getUnitOfVolume(LPDISPATCH retval)
{
	static BYTE parms[] =
		VTS_DISPATCH;
	InvokeHelper(0xb, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 retval);
}

void CUnitsManager::setUnitOfVolume(LPDISPATCH retval)
{
	static BYTE parms[] =
		VTS_DISPATCH;
	InvokeHelper(0xc, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 retval);
}

void CUnitsManager::getUnitOfDistanceGUI(LPDISPATCH retval)
{
	static BYTE parms[] =
		VTS_DISPATCH;
	InvokeHelper(0xd, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 retval);
}

void CUnitsManager::setUnitOfDistanceGUI(LPDISPATCH retval)
{
	static BYTE parms[] =
		VTS_DISPATCH;
	InvokeHelper(0xe, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 retval);
}

void CUnitsManager::getUnitOfForce(LPDISPATCH retval)
{
	static BYTE parms[] =
		VTS_DISPATCH;
	InvokeHelper(0xf, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 retval);
}

void CUnitsManager::setUnitOfForce(LPDISPATCH retval)
{
	static BYTE parms[] =
		VTS_DISPATCH;
	InvokeHelper(0x10, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 retval);
}

void CUnitsManager::getUnitOfMoment(LPDISPATCH retval)
{
	static BYTE parms[] =
		VTS_DISPATCH;
	InvokeHelper(0x11, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 retval);
}

void CUnitsManager::setUnitOfMoment(LPDISPATCH retval)
{
	static BYTE parms[] =
		VTS_DISPATCH;
	InvokeHelper(0x12, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 retval);
}

void CUnitsManager::getUnitOfWeightPerDistance(LPDISPATCH retval)
{
	static BYTE parms[] =
		VTS_DISPATCH;
	InvokeHelper(0x13, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 retval);
}

void CUnitsManager::setUnitOfWeightPerDistance(LPDISPATCH retval)
{
	static BYTE parms[] =
		VTS_DISPATCH;
	InvokeHelper(0x14, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 retval);
}

void CUnitsManager::getUnitOfAreaPerDistance(LPDISPATCH retval)
{
	static BYTE parms[] =
		VTS_DISPATCH;
	InvokeHelper(0x15, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 retval);
}

void CUnitsManager::setUnitOfAreaPerDistance(LPDISPATCH retval)
{
	static BYTE parms[] =
		VTS_DISPATCH;
	InvokeHelper(0x16, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 retval);
}

void CUnitsManager::doModalWithCaption(LPCTSTR caption)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x17, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 caption);
}

void CUnitsManager::doModalWithChooseFirstPage(long firstPageNo)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x18, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 firstPageNo);
}

void CUnitsManager::doModalUnitPage(long pageNo)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x19, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 pageNo);
}

void CUnitsManager::doModalUnitPages(long pagesSelection, long page)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4;
	InvokeHelper(0x1a, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 pagesSelection, page);
}

void CUnitsManager::doModalWithCaptionUnitPages(LPCTSTR caption, long pagesSelection, long page)
{
	static BYTE parms[] =
		VTS_BSTR VTS_I4 VTS_I4;
	InvokeHelper(0x1b, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 caption, pagesSelection, page);
}
